-- task 17 - Showing all employees and their positions
SELECT EMPLOYEES.ID,
       EMPLOYEES. NAME,
       POSITIONS.DESCRIPTION AS 'POSITION' FROM EMPLOYEES
    JOIN POSITIONS ON (EMPLOYEES.POSITION_ID = POSITIONS.ID);
