-- task 20 - Showing all rentals, customer name, vehicle name, and employee name
SELECT CUSTOMERS.NAME AS 'CUSTOMER NAME',
       CARS.NAME AS 'CAR MODEL NAME',
       EMPLOYEES.NAME AS 'EMPLOYEE NAME'
       FROM RENTAL 
       JOIN CUSTOMERS ON (RENTAL.CUSTOMER_ID = CUSTOMERS.ID)
       JOIN CARS ON (RENTAL.CAR_ID = CARS.ID)
       JOIN EMPLOYEES ON (RENTAL.EMPLOYEE_ID = EMPLOYEES.ID);